#!/usr/bin/env node
/*
 * Turns the capture's <id>.json sidecars into `src/tiny-tempo-trailer/clipData.ts`, so the
 * edit reads the game's own instants — each task's demonstration downbeat, its targets,
 * the moment the plaque appears — as typed constants rather than numbers someone retyped.
 *
 *   node tools/tiny-tempo/manifest.mjs
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const CLIPS = resolve(HERE, "..", "..", "public", "tiny-tempo", "clips");
const OUT = resolve(
  HERE,
  "..",
  "..",
  "src",
  "tiny-tempo-trailer",
  "clipData.ts",
);

const probe = (file) => {
  const run = spawnSync(
    "ffprobe",
    [
      "-v",
      "error",
      "-select_streams",
      "v:0",
      "-show_entries",
      "stream=width,height,nb_frames",
      "-of",
      "csv=p=0",
      file,
    ],
    { encoding: "utf8" },
  );
  if (run.status !== 0) throw new Error(`ffprobe failed on ${file}`);
  const [width, height, frames] = run.stdout.trim().split(",").map(Number);
  return { width, height, frames };
};

const round = (n) => Math.round(n * 1000) / 1000;
// Every clip, whether or not it has a sidecar: the website's act tiles, copied from the
// game's legal/acts/, carry no event times and need none.
const ids = [
  ...new Set(
    readdirSync(CLIPS)
      .filter((name) => /\.(mp4|json)$/.test(name))
      .map((name) => name.replace(/\.(mp4|json)$/, "")),
  ),
].sort();
const entries = ids.map((id) => {
  const sidecar = join(CLIPS, `${id}.json`);
  const meta = existsSync(sidecar)
    ? JSON.parse(readFileSync(sidecar, "utf8"))
    : { fps: 30, events: [] };
  const { width, height, frames } = probe(join(CLIPS, `${id}.mp4`));
  const tasks = meta.events
    .filter((e) => e.kind === "task")
    .map((e) => ({
      task: e.task,
      bpm: e.bpm,
      hits: e.hits,
      demo: round(e.demo),
      response: round(e.response),
      end: round(e.end),
      targets: e.targets.map(round),
    }));
  const summary = meta.events.find((e) => e.kind === "summary");
  return {
    id,
    file: `tiny-tempo/clips/${id}.mp4`,
    width,
    height,
    frames,
    seconds: round(frames / meta.fps),
    tasks,
    summaryAt: summary ? round(summary.at) : null,
  };
});

const lines = [
  "/* Generated by tools/tiny-tempo/manifest.mjs from public/tiny-tempo/clips/*.json. Do not edit. */",
  "",
  "export interface ClipTask {",
  "  readonly task: number;",
  "  readonly bpm: number;",
  "  readonly hits: number;",
  "  /** Clip seconds of the demonstration downbeat. */",
  "  readonly demo: number;",
  "  /** Clip seconds of the player's first target: their downbeat. */",
  "  readonly response: number;",
  "  readonly end: number;",
  "  readonly targets: readonly number[];",
  "}",
  "",
  "export interface ClipData {",
  "  readonly id: string;",
  "  readonly file: string;",
  "  readonly width: number;",
  "  readonly height: number;",
  "  readonly frames: number;",
  "  readonly seconds: number;",
  "  readonly tasks: readonly ClipTask[];",
  "  /** Clip seconds at which the result plaque appeared, when the clip runs to it. */",
  "  readonly summaryAt: number | null;",
  "}",
  "",
  "export const CLIP_DATA = {",
  ...entries.map((e) => `  ${e.id}: ${JSON.stringify(e)} as ClipData,`),
  "} as const;",
  "",
  "export type ClipId = keyof typeof CLIP_DATA;",
  "",
];
writeFileSync(OUT, lines.join("\n"));
console.log(`${entries.length} clip(s) -> ${OUT}`);
