"""
Measure a music track for a beat-cut edit.

    python3 tools/audio-envelope.py public/audio/tiny-tempo-home.wav src/tiny-tempo/teaser/envelope.ts

Prints the fitted tempo and beat offset, then a bar-by-bar table of how hard
each quarter note lands in the full band, the kick band (<150 Hz) and the hat
band (2-8 kHz). Writes a TypeScript module with per-frame loudness at 30 fps
so compositions can react to the music without decoding it at render time.

Needs numpy and scipy. Mono mixdown, 24-bit or 16-bit WAV in.
"""

import sys

import numpy as np
from scipy.io import wavfile
from scipy.signal import butter, sosfilt, stft

FPS = 30


def band_rms(signal, sr, lo=None, hi=None):
    if lo is None and hi is not None:
        sos = butter(4, hi, "low", fs=sr, output="sos")
    elif lo is not None and hi is None:
        sos = butter(4, lo, "high", fs=sr, output="sos")
    elif lo is not None and hi is not None:
        sos = butter(4, [lo, hi], "band", fs=sr, output="sos")
    else:
        sos = None
    x = sosfilt(sos, signal) if sos is not None else signal
    hop = sr // FPS
    n = len(x) // hop
    return np.array([np.sqrt(np.mean(x[i * hop : (i + 1) * hop] ** 2)) for i in range(n)])


def onset_envelope(signal, sr, hop=512):
    _, _, z = stft(signal, fs=sr, nperseg=2048, noverlap=2048 - hop)
    mag = np.log1p(np.abs(z) * 1000)
    flux = np.sum(np.maximum(mag[:, 1:] - mag[:, :-1], 0), axis=0)
    flux = np.concatenate([[0], flux])
    osr = sr / hop
    local = np.convolve(flux, np.ones(int(osr * 0.5)) / int(osr * 0.5), "same")
    return np.maximum(flux - local, 0), osr


def fit_grid(flux, osr, low, duration):
    """Tempo from the onset envelope, downbeat phase from the kick band."""
    best = None
    for period in np.arange(0.40, 1.00, 0.0002):
        times = np.arange(0, duration, period)
        idx = (times * osr).astype(int)
        idx = idx[idx < len(flux)]
        score = flux[idx].sum()
        if best is None or score > best[0]:
            best = (score, period)
    period = best[1]
    best = None
    for offset in np.arange(0, period, 1 / FPS / 2):
        frames = np.round(np.arange(offset, duration, period) * FPS).astype(int)
        frames = frames[frames < len(low)]
        score = low[frames].sum()
        if best is None or score > best[0]:
            best = (score, offset)
    return period, best[1]


def normalise(values, floor_db):
    db = 20 * np.log10(values + 1e-9)
    v = np.clip((db - floor_db) / (0 - floor_db), 0, 1)
    return v / max(v.max(), 1e-9)


def main(src, dst):
    sr, data = wavfile.read(src)
    data = data.astype(np.float64)
    if data.ndim == 2:
        data = data.mean(axis=1)
    data /= np.max(np.abs(data))
    duration = len(data) / sr

    rms = band_rms(data, sr)
    low = band_rms(data, sr, hi=150)
    hi = band_rms(data, sr, lo=2000, hi=8000)
    flux, osr = onset_envelope(data, sr)
    period, offset = fit_grid(flux, osr, low, duration)
    print(f"{duration:.2f} s, {60 / period:.2f} BPM, first beat at {offset:.3f} s")

    print("bar.beat   time   full  kick  hats   (dB, peak within the beat)")
    beats = np.arange(offset, duration, period)
    for i, t in enumerate(beats):
        f = int(round(t * FPS))
        seg = slice(max(0, f - 1), min(len(rms), f + 3))
        db = lambda a: int(round(20 * np.log10(a[seg].max() + 1e-9)))
        print(f"{i // 4:02d}.{i % 4}  {t:6.2f}   {db(rms):4d}  {db(low):4d}  {db(hi):4d}")

    rows = {
        "RMS": normalise(rms, -36),
        "LOW": normalise(low, -40),
        "HI": normalise(hi, -50),
    }
    out = [
        "/* Generated by tools/audio-envelope.py from " + src + ".",
        " * Per-frame loudness at 30 fps, normalised 0..1: full band, under 150 Hz",
        " * (kick and bass), 2-8 kHz (hats and air). Precomputed so a render is",
        " * deterministic and never decodes the audio at frame time. */",
        f"export const ENVELOPE_FPS = {FPS};",
    ]
    for name, values in rows.items():
        body = ", ".join(f"{v:.3f}" for v in values)
        out.append(f"export const {name}: readonly number[] = [\n  {body},\n];")
    with open(dst, "w") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {dst}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
