/* Generated by tools/tiny-tempo/manifest.mjs from public/tiny-tempo/clips/*.json. Do not edit. */

export interface ClipTask {
  readonly task: number;
  readonly bpm: number;
  readonly hits: number;
  /** Clip seconds of the demonstration downbeat. */
  readonly demo: number;
  /** Clip seconds of the player's first target: their downbeat. */
  readonly response: number;
  readonly end: number;
  readonly targets: readonly number[];
}

export interface ClipData {
  readonly id: string;
  readonly file: string;
  readonly width: number;
  readonly height: number;
  readonly frames: number;
  readonly seconds: number;
  readonly tasks: readonly ClipTask[];
  /** Clip seconds at which the result plaque appeared, when the clip runs to it. */
  readonly summaryAt: number | null;
}

export const CLIP_DATA = {
  level1: {
    id: "level1",
    file: "tiny-tempo/clips/level1.mp4",
    width: 1212,
    height: 2154,
    frames: 806,
    seconds: 26.867,
    tasks: [
      {
        task: 0,
        bpm: 120,
        hits: 3,
        demo: 1,
        response: 3,
        end: 5,
        targets: [3, 4, 4.5],
      },
      {
        task: 1,
        bpm: 120,
        hits: 3,
        demo: 7,
        response: 9,
        end: 11,
        targets: [9, 9.5, 10.5],
      },
      {
        task: 2,
        bpm: 120,
        hits: 3,
        demo: 13,
        response: 15,
        end: 17,
        targets: [15, 15.5, 16],
      },
    ],
    summaryAt: 18.867,
  } as ClipData,
  level19: {
    id: "level19",
    file: "tiny-tempo/clips/level19.mp4",
    width: 1212,
    height: 2154,
    frames: 360,
    seconds: 12,
    tasks: [
      {
        task: 3,
        bpm: 130,
        hits: 4,
        demo: 1,
        response: 2.846,
        end: 4.692,
        targets: [2.846, 3.538, 3.769, 4.461],
      },
      {
        task: 4,
        bpm: 133,
        hits: 8,
        demo: 8.384,
        response: 11.993,
        end: 15.602,
        targets: [11.993, 12.67, 12.895, 13.347, 13.798, 14.474, 14.7, 15.151],
      },
    ],
    summaryAt: null,
  } as ClipData,
  level20: {
    id: "level20",
    file: "tiny-tempo/clips/level20.mp4",
    width: 1212,
    height: 2154,
    frames: 360,
    seconds: 12,
    tasks: [
      {
        task: 3,
        bpm: 131,
        hits: 4,
        demo: 1,
        response: 2.832,
        end: 4.664,
        targets: [2.832, 3.29, 3.977, 4.435],
      },
      {
        task: 4,
        bpm: 134,
        hits: 8,
        demo: 8.328,
        response: 11.911,
        end: 15.493,
        targets: [
          11.911, 12.582, 12.806, 13.254, 13.702, 14.373, 14.597, 15.045,
        ],
      },
    ],
    summaryAt: null,
  } as ClipData,
  level28: {
    id: "level28",
    file: "tiny-tempo/clips/level28.mp4",
    width: 1212,
    height: 2154,
    frames: 420,
    seconds: 14,
    tasks: [
      {
        task: 3,
        bpm: 132,
        hits: 9,
        demo: 1,
        response: 4.637,
        end: 8.273,
        targets: [4.637, 5.091, 5.318, 5.773, 6, 6.455, 6.909, 7.137, 7.818],
      },
      {
        task: 4,
        bpm: 136,
        hits: 10,
        demo: 10.091,
        response: 13.62,
        end: 17.15,
        targets: [
          13.62, 14.062, 14.282, 14.723, 15.165, 15.385, 16.047, 16.268, 16.709,
          16.929,
        ],
      },
    ],
    summaryAt: null,
  } as ClipData,
  level5: {
    id: "level5",
    file: "tiny-tempo/clips/level5.mp4",
    width: 1212,
    height: 2154,
    frames: 390,
    seconds: 13,
    tasks: [
      {
        task: 0,
        bpm: 120,
        hits: 3,
        demo: 1,
        response: 3,
        end: 5,
        targets: [3, 3.5, 4],
      },
      {
        task: 1,
        bpm: 120,
        hits: 4,
        demo: 7,
        response: 9,
        end: 11,
        targets: [9, 9.5, 10, 10.5],
      },
      {
        task: 2,
        bpm: 120,
        hits: 3,
        demo: 13,
        response: 15,
        end: 17,
        targets: [15, 15.5, 16.5],
      },
    ],
    summaryAt: null,
  } as ClipData,
  map: {
    id: "map",
    file: "tiny-tempo/clips/map.mp4",
    width: 1212,
    height: 2154,
    frames: 180,
    seconds: 6,
    tasks: [],
    summaryAt: null,
  } as ClipData,
  menu: {
    id: "menu",
    file: "tiny-tempo/clips/menu.mp4",
    width: 1212,
    height: 2154,
    frames: 240,
    seconds: 8,
    tasks: [],
    summaryAt: null,
  } as ClipData,
  menuClean: {
    id: "menuClean",
    file: "tiny-tempo/clips/menuClean.mp4",
    width: 1212,
    height: 2154,
    frames: 240,
    seconds: 8,
    tasks: [],
    summaryAt: null,
  } as ClipData,
  plaque20: {
    id: "plaque20",
    file: "tiny-tempo/clips/plaque20.mp4",
    width: 1212,
    height: 2154,
    frames: 270,
    seconds: 9,
    tasks: [],
    summaryAt: 0,
  } as ClipData,
  tileBarber: {
    id: "tileBarber",
    file: "tiny-tempo/clips/tileBarber.mp4",
    width: 432,
    height: 532,
    frames: 240,
    seconds: 8,
    tasks: [],
    summaryAt: null,
  } as ClipData,
  tileBell: {
    id: "tileBell",
    file: "tiny-tempo/clips/tileBell.mp4",
    width: 432,
    height: 532,
    frames: 240,
    seconds: 8,
    tasks: [],
    summaryAt: null,
  } as ClipData,
  tileBongos: {
    id: "tileBongos",
    file: "tiny-tempo/clips/tileBongos.mp4",
    width: 432,
    height: 532,
    frames: 240,
    seconds: 8,
    tasks: [],
    summaryAt: null,
  } as ClipData,
  tileDoorbell: {
    id: "tileDoorbell",
    file: "tiny-tempo/clips/tileDoorbell.mp4",
    width: 432,
    height: 532,
    frames: 240,
    seconds: 8,
    tasks: [],
    summaryAt: null,
  } as ClipData,
  tilePopcorn: {
    id: "tilePopcorn",
    file: "tiny-tempo/clips/tilePopcorn.mp4",
    width: 432,
    height: 532,
    frames: 240,
    seconds: 8,
    tasks: [],
    summaryAt: null,
  } as ClipData,
  tileSlushy: {
    id: "tileSlushy",
    file: "tiny-tempo/clips/tileSlushy.mp4",
    width: 432,
    height: 532,
    frames: 240,
    seconds: 8,
    tasks: [],
    summaryAt: null,
  } as ClipData,
  level9: {
    id: "level9",
    file: "tiny-tempo/clips/level9.mp4",
    width: 1212,
    height: 2154,
    frames: 720,
    seconds: 24.0,
    tasks: [
      {
        task: 0,
        bpm: 120,
        hits: 3,
        demo: 1,
        response: 3,
        end: 5,
        targets: [3, 3.5, 4],
      },
      {
        task: 2,
        bpm: 127,
        hits: 4,
        demo: 1,
        response: 3,
        end: 5,
        targets: [3, 3.5, 4],
      },
      {
        task: 3,
        bpm: 132,
        hits: 8,
        demo: 1,
        response: 5,
        end: 9,
        targets: [5],
      },
    ],
    summaryAt: null,
  } as ClipData,
} as const;

export type ClipId = keyof typeof CLIP_DATA;
